### ISSUE TITLE
EULA serialization produces bad path on Mac

### ISSUE THREAD

**Issue by ralfbiedert** [Tobii/UnitySDK#1]
When accepting the EULA on a Mac (probably Linux as well), weird paths are being produced.

Probably due to hardcoding `\` instead of using a proper path separator. 

![screen shot 2017-05-31 at 15 01 27](https://cloud.githubusercontent.com/assets/301288/26632981/2fcfaa10-4612-11e7-8978-ebb3b0b9a73b.png)

**Comment by alex8b** [comment]
Fixed in 3.0.8
