### ISSUE TITLE
GazePoint.ToString() exception

### ISSUE THREAD

**Issue by vestigialdev** [Tobii/UnitySDK#4]
Hi, in GazePoint.cs on line 136

`public override string ToString()
{
return string.Format("{0} {1} {2}", Screen, Timestamp);
}`

it seems to be expecting three values, but only two are given, so .ToString() will cause an exception every time.

**Comment by alex8b** [comment]
Fixed in 4.0.4
Download at:
https://developer.tobii.com/consumer-eye-trackers/unity-sdk/
